// 
// Decompiled by Procyon v0.5.29
// 

package com.vontu.util.jdbc;

import java.sql.SQLWarning;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.sql.SQLException;
import com.vontu.util.Stopwatch;
import java.sql.Statement;

public class LoggingStatement implements Statement
{
    private Statement _statement;
    protected Stopwatch _stopWatch;
    protected final JDBCLogger _logger;
    private static volatile int _totalStatementsExecuted;
    
    public LoggingStatement(final Statement statement, final JDBCLogger logger) {
        this._stopWatch = new Stopwatch("LoggingStatement");
        this._statement = statement;
        this._logger = logger;
    }
    
    public Statement getDelegateStatement() {
        return this._statement;
    }
    
    @Override
    public void addBatch(final String sql) throws SQLException {
        this._statement.addBatch(sql);
    }
    
    @Override
    public void cancel() throws SQLException {
        this._statement.cancel();
    }
    
    @Override
    public void clearBatch() throws SQLException {
        this._statement.clearBatch();
    }
    
    @Override
    public void clearWarnings() throws SQLException {
        this._statement.clearWarnings();
    }
    
    @Override
    public void close() throws SQLException {
        this._statement.close();
    }
    
    @Override
    public boolean isClosed() throws SQLException {
        return this._statement.isClosed();
    }
    
    @Override
    public void setPoolable(final boolean poolable) throws SQLException {
        this._statement.setPoolable(poolable);
    }
    
    @Override
    public boolean isPoolable() throws SQLException {
        return this._statement.isPoolable();
    }
    
    @Override
    public boolean execute(final String sql) throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementBeginMessage(sql, queryNumber));
                this._stopWatch.start();
                final boolean result = this._statement.execute(sql);
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage(sql, e));
                throw e;
            }
        }
        return this._statement.execute(sql);
    }
    
    @Override
    public boolean execute(final String sql, final int autoGeneratedKeys) throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementBeginMessage(sql, queryNumber));
                this._stopWatch.start();
                final boolean result = this._statement.execute(sql, autoGeneratedKeys);
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage(sql, e));
                throw e;
            }
        }
        return this._statement.execute(sql, autoGeneratedKeys);
    }
    
    @Override
    public boolean execute(final String sql, final int[] columnIndexes) throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementBeginMessage(sql, queryNumber));
                this._stopWatch.start();
                final boolean result = this._statement.execute(sql, columnIndexes);
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage(sql, e));
                throw e;
            }
        }
        return this._statement.execute(sql, columnIndexes);
    }
    
    @Override
    public boolean execute(final String sql, final String[] columnNames) throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementBeginMessage(sql, queryNumber));
                this._stopWatch.start();
                final boolean result = this._statement.execute(sql, columnNames);
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage(sql, e));
                throw e;
            }
        }
        return this._statement.execute(sql, columnNames);
    }
    
    @Override
    public int[] executeBatch() throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementBeginMessage("Batch execute performed", queryNumber));
                this._stopWatch.start();
                final int[] result = this._statement.executeBatch();
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateStatementEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage("Batch execute performed", e));
                throw e;
            }
        }
        return this._statement.executeBatch();
    }
    
    @Override
    public ResultSet executeQuery(final String sql) throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateQueryBeginMessage(sql, queryNumber));
                this._stopWatch.start();
                final ResultSet result = new LoggingResultSet(this._statement.executeQuery(sql), queryNumber, this._logger);
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateQueryEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage(sql, e));
                throw e;
            }
        }
        return this._statement.executeQuery(sql);
    }
    
    @Override
    public int executeUpdate(final String sql) throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateUpdateBeginMessage(sql, queryNumber));
                this._stopWatch.start();
                final int result = this._statement.executeUpdate(sql);
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateUpdateEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage(sql, e));
                throw e;
            }
        }
        return this._statement.executeUpdate(sql);
    }
    
    @Override
    public int executeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateUpdateBeginMessage(sql, queryNumber));
                this._stopWatch.start();
                final int result = this._statement.executeUpdate(sql, autoGeneratedKeys);
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateUpdateEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage(sql, e));
                throw e;
            }
        }
        return this._statement.executeUpdate(sql, autoGeneratedKeys);
    }
    
    @Override
    public int executeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateUpdateBeginMessage(sql, queryNumber));
                this._stopWatch.start();
                final int result = this._statement.executeUpdate(sql, columnIndexes);
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateUpdateEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage(sql, e));
                throw e;
            }
        }
        return this._statement.executeUpdate(sql, columnIndexes);
    }
    
    @Override
    public int executeUpdate(final String sql, final String[] columnNames) throws SQLException {
        if (this._logger.isLoggable(Level.FINE)) {
            try {
                final int queryNumber = this.incrementStatementNumber();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateUpdateBeginMessage(sql, queryNumber));
                this._stopWatch.start();
                final int result = this._statement.executeUpdate(sql, columnNames);
                final Stopwatch.Statistics statistics = this._stopWatch.stop();
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateUpdateEndMessage(statistics, queryNumber));
                return result;
            }
            catch (SQLException e) {
                this._logger.log(Level.FINE, StatementLoggingFormatter.generateFailedMessage(sql, e));
                throw e;
            }
        }
        return this._statement.executeUpdate(sql, columnNames);
    }
    
    @Override
    public Connection getConnection() throws SQLException {
        return this._statement.getConnection();
    }
    
    @Override
    public int getFetchDirection() throws SQLException {
        return this._statement.getFetchDirection();
    }
    
    @Override
    public int getFetchSize() throws SQLException {
        return this._statement.getFetchSize();
    }
    
    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return this._statement.getGeneratedKeys();
    }
    
    @Override
    public int getMaxFieldSize() throws SQLException {
        return this._statement.getMaxFieldSize();
    }
    
    @Override
    public int getMaxRows() throws SQLException {
        return this._statement.getMaxRows();
    }
    
    @Override
    public boolean getMoreResults() throws SQLException {
        return this._statement.getMoreResults();
    }
    
    @Override
    public boolean getMoreResults(final int current) throws SQLException {
        return this._statement.getMoreResults(current);
    }
    
    @Override
    public int getQueryTimeout() throws SQLException {
        return this._statement.getQueryTimeout();
    }
    
    @Override
    public ResultSet getResultSet() throws SQLException {
        return this._statement.getResultSet();
    }
    
    @Override
    public int getResultSetConcurrency() throws SQLException {
        return this._statement.getResultSetConcurrency();
    }
    
    @Override
    public int getResultSetHoldability() throws SQLException {
        return this._statement.getResultSetHoldability();
    }
    
    @Override
    public int getResultSetType() throws SQLException {
        return this._statement.getResultSetType();
    }
    
    @Override
    public int getUpdateCount() throws SQLException {
        return this._statement.getUpdateCount();
    }
    
    @Override
    public SQLWarning getWarnings() throws SQLException {
        return this._statement.getWarnings();
    }
    
    @Override
    public void setCursorName(final String name) throws SQLException {
        this._statement.setCursorName(name);
    }
    
    @Override
    public void setEscapeProcessing(final boolean enable) throws SQLException {
        this._statement.setEscapeProcessing(enable);
    }
    
    @Override
    public void setFetchDirection(final int direction) throws SQLException {
        this._statement.setFetchDirection(direction);
    }
    
    @Override
    public void setFetchSize(final int rows) throws SQLException {
        this._statement.setFetchSize(rows);
    }
    
    @Override
    public void setMaxFieldSize(final int max) throws SQLException {
        this._statement.setMaxFieldSize(max);
    }
    
    @Override
    public void setMaxRows(final int max) throws SQLException {
        this._statement.setMaxRows(max);
    }
    
    @Override
    public void setQueryTimeout(final int seconds) throws SQLException {
        this._statement.setQueryTimeout(seconds);
    }
    
    protected int incrementStatementNumber() {
        return LoggingStatement._totalStatementsExecuted++;
    }
    
    @Override
    public boolean isWrapperFor(final Class<?> iface) throws SQLException {
        return iface.isAssignableFrom(this.getClass()) || this._statement.isWrapperFor(iface);
    }
    
    @Override
    public <T> T unwrap(final Class<T> iface) throws SQLException {
        if (iface.isAssignableFrom(this.getClass())) {
            return (T)this;
        }
        return this._statement.unwrap(iface);
    }
    
    @Override
    public void closeOnCompletion() throws SQLException {
        this._statement.closeOnCompletion();
    }
    
    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return this._statement.isCloseOnCompletion();
    }
    
    static {
        LoggingStatement._totalStatementsExecuted = 1;
    }
}
