// 
// Decompiled by Procyon v0.5.29
// 

package com.vontu.util.jdbc.i18n;

import java.sql.SQLWarning;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class LocalizedStatement implements Statement
{
    private Statement _statement;
    private LocalizedConnection _connection;
    
    public LocalizedStatement(final Statement s, final LocalizedConnection creator) {
        this._statement = s;
        this._connection = creator;
    }
    
    @Override
    public void addBatch(final String sql) throws SQLException {
        this._statement.addBatch(sql);
    }
    
    @Override
    public void cancel() throws SQLException {
        this._statement.cancel();
    }
    
    @Override
    public void clearBatch() throws SQLException {
        this._statement.clearBatch();
    }
    
    @Override
    public void clearWarnings() throws SQLException {
        this._statement.clearWarnings();
    }
    
    @Override
    public void close() throws SQLException {
        this._statement.close();
    }
    
    @Override
    public boolean execute(final String sql) throws SQLException {
        return this._statement.execute(sql);
    }
    
    @Override
    public boolean execute(final String sql, final int autoGeneratedKeys) throws SQLException {
        return this._statement.execute(sql, autoGeneratedKeys);
    }
    
    @Override
    public boolean execute(final String sql, final int[] columnIndexes) throws SQLException {
        return this._statement.execute(sql, columnIndexes);
    }
    
    @Override
    public boolean execute(final String sql, final String[] columnNames) throws SQLException {
        return this._statement.execute(sql, columnNames);
    }
    
    @Override
    public int[] executeBatch() throws SQLException {
        return this._statement.executeBatch();
    }
    
    @Override
    public ResultSet executeQuery(final String sql) throws SQLException {
        final ResultSet rs = this._statement.executeQuery(sql);
        return new LocalizedResultSet(rs, this);
    }
    
    @Override
    public int executeUpdate(final String sql) throws SQLException {
        return this._statement.executeUpdate(sql);
    }
    
    @Override
    public int executeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
        return this._statement.executeUpdate(sql, autoGeneratedKeys);
    }
    
    @Override
    public int executeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
        return this._statement.executeUpdate(sql, columnIndexes);
    }
    
    @Override
    public int executeUpdate(final String sql, final String[] columnNames) throws SQLException {
        return this._statement.executeUpdate(sql, columnNames);
    }
    
    @Override
    public Connection getConnection() throws SQLException {
        return this._connection;
    }
    
    @Override
    public int getFetchDirection() throws SQLException {
        return this._statement.getFetchDirection();
    }
    
    @Override
    public int getFetchSize() throws SQLException {
        return this._statement.getFetchSize();
    }
    
    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        final ResultSet rs = this._statement.getGeneratedKeys();
        return new LocalizedResultSet(rs, this);
    }
    
    @Override
    public int getMaxFieldSize() throws SQLException {
        return this._statement.getMaxFieldSize();
    }
    
    @Override
    public int getMaxRows() throws SQLException {
        return this._statement.getMaxRows();
    }
    
    @Override
    public boolean getMoreResults() throws SQLException {
        return this._statement.getMoreResults();
    }
    
    @Override
    public boolean getMoreResults(final int current) throws SQLException {
        return this._statement.getMoreResults(current);
    }
    
    @Override
    public int getQueryTimeout() throws SQLException {
        return this._statement.getQueryTimeout();
    }
    
    @Override
    public ResultSet getResultSet() throws SQLException {
        final ResultSet rs = this._statement.getResultSet();
        return new LocalizedResultSet(rs, this);
    }
    
    @Override
    public int getResultSetConcurrency() throws SQLException {
        return this._statement.getResultSetConcurrency();
    }
    
    @Override
    public int getResultSetHoldability() throws SQLException {
        return this._statement.getResultSetHoldability();
    }
    
    @Override
    public int getResultSetType() throws SQLException {
        return this._statement.getResultSetType();
    }
    
    @Override
    public int getUpdateCount() throws SQLException {
        return this._statement.getUpdateCount();
    }
    
    @Override
    public SQLWarning getWarnings() throws SQLException {
        return this._statement.getWarnings();
    }
    
    @Override
    public boolean isClosed() throws SQLException {
        return this._statement.isClosed();
    }
    
    @Override
    public boolean isPoolable() throws SQLException {
        return this._statement.isPoolable();
    }
    
    @Override
    public void setCursorName(final String name) throws SQLException {
        this._statement.setCursorName(name);
    }
    
    @Override
    public void setEscapeProcessing(final boolean enable) throws SQLException {
        this._statement.setEscapeProcessing(enable);
    }
    
    @Override
    public void setFetchDirection(final int direction) throws SQLException {
        this._statement.setFetchDirection(direction);
    }
    
    @Override
    public void setFetchSize(final int rows) throws SQLException {
        this._statement.setFetchSize(rows);
    }
    
    @Override
    public void setMaxFieldSize(final int max) throws SQLException {
        this._statement.setMaxFieldSize(max);
    }
    
    @Override
    public void setMaxRows(final int max) throws SQLException {
        this._statement.setMaxRows(max);
    }
    
    @Override
    public void setPoolable(final boolean poolable) throws SQLException {
        this._statement.setPoolable(poolable);
    }
    
    @Override
    public void setQueryTimeout(final int seconds) throws SQLException {
        this._statement.setQueryTimeout(seconds);
    }
    
    @Override
    public boolean isWrapperFor(final Class<?> iface) throws SQLException {
        return iface.isAssignableFrom(this.getClass()) || this._statement.isWrapperFor(iface);
    }
    
    @Override
    public <T> T unwrap(final Class<T> iface) throws SQLException {
        if (iface.isAssignableFrom(this.getClass())) {
            return (T)this;
        }
        return this._statement.unwrap(iface);
    }
    
    @Override
    public void closeOnCompletion() throws SQLException {
        this._statement.closeOnCompletion();
    }
    
    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return this._statement.isCloseOnCompletion();
    }
}
