// 
// Decompiled by Procyon v0.5.29
// 

package com.vontu.util.jdbc.i18n;

import java.util.Map;
import java.net.URL;
import java.sql.Timestamp;
import java.sql.Time;
import java.sql.SQLXML;
import java.sql.RowId;
import java.sql.Ref;
import java.sql.NClob;
import java.util.Calendar;
import java.sql.Date;
import java.sql.Clob;
import java.io.Reader;
import java.sql.Blob;
import java.math.BigDecimal;
import java.io.InputStream;
import java.sql.Array;
import java.sql.ParameterMetaData;
import java.sql.ResultSetMetaData;
import java.sql.SQLWarning;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.CallableStatement;

public class LocalizedCallableStatement implements CallableStatement
{
    private CallableStatement _statement;
    private LocalizedConnection _connection;
    
    public LocalizedCallableStatement(final CallableStatement cs, final LocalizedConnection localizedConnection) {
        this._statement = cs;
        this._connection = localizedConnection;
    }
    
    @Override
    public void addBatch(final String sql) throws SQLException {
        this._statement.addBatch(sql);
    }
    
    @Override
    public void cancel() throws SQLException {
        this._statement.cancel();
    }
    
    @Override
    public void clearBatch() throws SQLException {
        this._statement.clearBatch();
    }
    
    @Override
    public void clearWarnings() throws SQLException {
        this._statement.clearWarnings();
    }
    
    @Override
    public void close() throws SQLException {
        this._statement.close();
    }
    
    @Override
    public boolean execute(final String sql) throws SQLException {
        return this._statement.execute(sql);
    }
    
    @Override
    public boolean execute(final String sql, final int autoGeneratedKeys) throws SQLException {
        return this._statement.execute(sql, autoGeneratedKeys);
    }
    
    @Override
    public boolean execute(final String sql, final int[] columnIndexes) throws SQLException {
        return this._statement.execute(sql, columnIndexes);
    }
    
    @Override
    public boolean execute(final String sql, final String[] columnNames) throws SQLException {
        return this._statement.execute(sql, columnNames);
    }
    
    @Override
    public int[] executeBatch() throws SQLException {
        return this._statement.executeBatch();
    }
    
    @Override
    public ResultSet executeQuery(final String sql) throws SQLException {
        final ResultSet rs = this._statement.executeQuery(sql);
        return new LocalizedResultSet(rs, this);
    }
    
    @Override
    public int executeUpdate(final String sql) throws SQLException {
        return this._statement.executeUpdate(sql);
    }
    
    @Override
    public int executeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
        return this._statement.executeUpdate(sql, autoGeneratedKeys);
    }
    
    @Override
    public int executeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
        return this._statement.executeUpdate(sql, columnIndexes);
    }
    
    @Override
    public int executeUpdate(final String sql, final String[] columnNames) throws SQLException {
        return this._statement.executeUpdate(sql, columnNames);
    }
    
    @Override
    public Connection getConnection() throws SQLException {
        return this._connection;
    }
    
    @Override
    public int getFetchDirection() throws SQLException {
        return this._statement.getFetchDirection();
    }
    
    @Override
    public int getFetchSize() throws SQLException {
        return this._statement.getFetchSize();
    }
    
    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        final ResultSet rs = this._statement.getGeneratedKeys();
        return new LocalizedResultSet(rs, this);
    }
    
    @Override
    public int getMaxFieldSize() throws SQLException {
        return this._statement.getMaxFieldSize();
    }
    
    @Override
    public int getMaxRows() throws SQLException {
        return this._statement.getMaxRows();
    }
    
    @Override
    public boolean getMoreResults() throws SQLException {
        return this._statement.getMoreResults();
    }
    
    @Override
    public boolean getMoreResults(final int current) throws SQLException {
        return this._statement.getMoreResults(current);
    }
    
    @Override
    public int getQueryTimeout() throws SQLException {
        return this._statement.getQueryTimeout();
    }
    
    @Override
    public ResultSet getResultSet() throws SQLException {
        final ResultSet rs = this._statement.getResultSet();
        return new LocalizedResultSet(rs, this);
    }
    
    @Override
    public int getResultSetConcurrency() throws SQLException {
        return this._statement.getResultSetConcurrency();
    }
    
    @Override
    public int getResultSetHoldability() throws SQLException {
        return this._statement.getResultSetHoldability();
    }
    
    @Override
    public int getResultSetType() throws SQLException {
        return this._statement.getResultSetType();
    }
    
    @Override
    public int getUpdateCount() throws SQLException {
        return this._statement.getUpdateCount();
    }
    
    @Override
    public SQLWarning getWarnings() throws SQLException {
        return this._statement.getWarnings();
    }
    
    @Override
    public boolean isClosed() throws SQLException {
        return this._statement.isClosed();
    }
    
    @Override
    public boolean isPoolable() throws SQLException {
        return this._statement.isPoolable();
    }
    
    @Override
    public void setCursorName(final String name) throws SQLException {
        this._statement.setCursorName(name);
    }
    
    @Override
    public void setEscapeProcessing(final boolean enable) throws SQLException {
        this._statement.setEscapeProcessing(enable);
    }
    
    @Override
    public void setFetchDirection(final int direction) throws SQLException {
        this._statement.setFetchDirection(direction);
    }
    
    @Override
    public void setFetchSize(final int rows) throws SQLException {
        this._statement.setFetchSize(rows);
    }
    
    @Override
    public void setMaxFieldSize(final int max) throws SQLException {
        this._statement.setMaxFieldSize(max);
    }
    
    @Override
    public void setMaxRows(final int max) throws SQLException {
        this._statement.setMaxRows(max);
    }
    
    @Override
    public void setPoolable(final boolean poolable) throws SQLException {
        this._statement.setPoolable(poolable);
    }
    
    @Override
    public void setQueryTimeout(final int seconds) throws SQLException {
        this._statement.setQueryTimeout(seconds);
    }
    
    @Override
    public boolean isWrapperFor(final Class<?> iface) throws SQLException {
        return iface.isAssignableFrom(this.getClass()) || this._statement.isWrapperFor(iface);
    }
    
    @Override
    public <T> T unwrap(final Class<T> iface) throws SQLException {
        if (iface.isAssignableFrom(this.getClass())) {
            return (T)this;
        }
        return this._statement.unwrap(iface);
    }
    
    @Override
    public void addBatch() throws SQLException {
        this._statement.addBatch();
    }
    
    @Override
    public void clearParameters() throws SQLException {
        this._statement.clearParameters();
    }
    
    @Override
    public boolean execute() throws SQLException {
        return this._statement.execute();
    }
    
    @Override
    public ResultSet executeQuery() throws SQLException {
        final ResultSet rs = this._statement.executeQuery();
        return new LocalizedResultSet(rs, this);
    }
    
    @Override
    public int executeUpdate() throws SQLException {
        return this._statement.executeUpdate();
    }
    
    @Override
    public ResultSetMetaData getMetaData() throws SQLException {
        return this._statement.getMetaData();
    }
    
    @Override
    public ParameterMetaData getParameterMetaData() throws SQLException {
        return this._statement.getParameterMetaData();
    }
    
    @Override
    public void setArray(final int parameterIndex, final Array x) throws SQLException {
        this._statement.setArray(parameterIndex, x);
    }
    
    @Override
    public void setAsciiStream(final int parameterIndex, final InputStream x) throws SQLException {
        this._statement.setAsciiStream(parameterIndex, x);
    }
    
    @Override
    public void setAsciiStream(final int parameterIndex, final InputStream x, final int length) throws SQLException {
        this._statement.setAsciiStream(parameterIndex, x, length);
    }
    
    @Override
    public void setAsciiStream(final int parameterIndex, final InputStream x, final long length) throws SQLException {
        this._statement.setAsciiStream(parameterIndex, x, length);
    }
    
    @Override
    public void setBigDecimal(final int parameterIndex, final BigDecimal x) throws SQLException {
        this._statement.setBigDecimal(parameterIndex, x);
    }
    
    @Override
    public void setBinaryStream(final int parameterIndex, final InputStream x) throws SQLException {
        this._statement.setBinaryStream(parameterIndex, x);
    }
    
    @Override
    public void setBinaryStream(final int parameterIndex, final InputStream x, final int length) throws SQLException {
        this._statement.setBinaryStream(parameterIndex, x, length);
    }
    
    @Override
    public void setBinaryStream(final int parameterIndex, final InputStream x, final long length) throws SQLException {
        this._statement.setBinaryStream(parameterIndex, x, length);
    }
    
    @Override
    public void setBlob(final int parameterIndex, final Blob x) throws SQLException {
        this._statement.setBlob(parameterIndex, x);
    }
    
    @Override
    public void setBlob(final int parameterIndex, final InputStream inputStream) throws SQLException {
        this._statement.setBlob(parameterIndex, inputStream);
    }
    
    @Override
    public void setBlob(final int parameterIndex, final InputStream inputStream, final long length) throws SQLException {
        this._statement.setBlob(parameterIndex, inputStream, length);
    }
    
    @Override
    public void setBoolean(final int parameterIndex, final boolean x) throws SQLException {
        this._statement.setBoolean(parameterIndex, x);
    }
    
    @Override
    public void setByte(final int parameterIndex, final byte x) throws SQLException {
        this._statement.setByte(parameterIndex, x);
    }
    
    @Override
    public void setBytes(final int parameterIndex, final byte[] x) throws SQLException {
        this._statement.setBytes(parameterIndex, x);
    }
    
    @Override
    public void setCharacterStream(final int parameterIndex, final Reader reader) throws SQLException {
        this._statement.setCharacterStream(parameterIndex, reader);
    }
    
    @Override
    public void setCharacterStream(final int parameterIndex, final Reader reader, final int length) throws SQLException {
        this._statement.setCharacterStream(parameterIndex, reader, length);
    }
    
    @Override
    public void setCharacterStream(final int parameterIndex, final Reader reader, final long length) throws SQLException {
        this._statement.setCharacterStream(parameterIndex, reader, length);
    }
    
    @Override
    public void setClob(final int parameterIndex, final Clob x) throws SQLException {
        this._statement.setClob(parameterIndex, x);
    }
    
    @Override
    public void setClob(final int parameterIndex, final Reader reader) throws SQLException {
        this._statement.setClob(parameterIndex, reader);
    }
    
    @Override
    public void setClob(final int parameterIndex, final Reader reader, final long length) throws SQLException {
        this._statement.setClob(parameterIndex, reader, length);
    }
    
    @Override
    public void setDate(final int parameterIndex, final Date x) throws SQLException {
        this._statement.setDate(parameterIndex, x);
    }
    
    @Override
    public void setDate(final int parameterIndex, final Date x, final Calendar cal) throws SQLException {
        this._statement.setDate(parameterIndex, x, cal);
    }
    
    @Override
    public void setDouble(final int parameterIndex, final double x) throws SQLException {
        this._statement.setDouble(parameterIndex, x);
    }
    
    @Override
    public void setFloat(final int parameterIndex, final float x) throws SQLException {
        this._statement.setFloat(parameterIndex, x);
    }
    
    @Override
    public void setInt(final int parameterIndex, final int x) throws SQLException {
        this._statement.setInt(parameterIndex, x);
    }
    
    @Override
    public void setLong(final int parameterIndex, final long x) throws SQLException {
        this._statement.setLong(parameterIndex, x);
    }
    
    @Override
    public void setNCharacterStream(final int parameterIndex, final Reader value) throws SQLException {
        this._statement.setNCharacterStream(parameterIndex, value);
    }
    
    @Override
    public void setNCharacterStream(final int parameterIndex, final Reader value, final long length) throws SQLException {
        this._statement.setNCharacterStream(parameterIndex, value, length);
    }
    
    @Override
    public void setNClob(final int parameterIndex, final NClob value) throws SQLException {
        this._statement.setNClob(parameterIndex, value);
    }
    
    @Override
    public void setNClob(final int parameterIndex, final Reader reader) throws SQLException {
        this._statement.setNClob(parameterIndex, reader);
    }
    
    @Override
    public void setNClob(final int parameterIndex, final Reader reader, final long length) throws SQLException {
        this._statement.setNClob(parameterIndex, reader, length);
    }
    
    @Override
    public void setNString(final int parameterIndex, final String value) throws SQLException {
        this._statement.setNString(parameterIndex, value);
    }
    
    @Override
    public void setNull(final int parameterIndex, final int sqlType) throws SQLException {
        this._statement.setNull(parameterIndex, sqlType);
    }
    
    @Override
    public void setNull(final int parameterIndex, final int sqlType, final String typeName) throws SQLException {
        this._statement.setNull(parameterIndex, sqlType, typeName);
    }
    
    @Override
    public void setObject(final int parameterIndex, final Object x) throws SQLException {
        this._statement.setObject(parameterIndex, x);
    }
    
    @Override
    public void setObject(final int parameterIndex, final Object x, final int targetSqlType) throws SQLException {
        this._statement.setObject(parameterIndex, x, targetSqlType);
    }
    
    @Override
    public void setObject(final int parameterIndex, final Object x, final int targetSqlType, final int scaleOrLength) throws SQLException {
        this._statement.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
    }
    
    @Override
    public void setRef(final int parameterIndex, final Ref x) throws SQLException {
        this._statement.setRef(parameterIndex, x);
    }
    
    @Override
    public void setRowId(final int parameterIndex, final RowId x) throws SQLException {
        this._statement.setRowId(parameterIndex, x);
    }
    
    @Override
    public void setSQLXML(final int parameterIndex, final SQLXML xmlObject) throws SQLException {
        this._statement.setSQLXML(parameterIndex, xmlObject);
    }
    
    @Override
    public void setShort(final int parameterIndex, final short x) throws SQLException {
        this._statement.setShort(parameterIndex, x);
    }
    
    @Override
    public void setString(final int parameterIndex, final String x) throws SQLException {
        this._statement.setString(parameterIndex, x);
    }
    
    @Override
    public void setTime(final int parameterIndex, final Time x) throws SQLException {
        this._statement.setTime(parameterIndex, x);
    }
    
    @Override
    public void setTime(final int parameterIndex, final Time x, final Calendar cal) throws SQLException {
        this._statement.setTime(parameterIndex, x, cal);
    }
    
    @Override
    public void setTimestamp(final int parameterIndex, final Timestamp x) throws SQLException {
        this._statement.setTimestamp(parameterIndex, x);
    }
    
    @Override
    public void setTimestamp(final int parameterIndex, final Timestamp x, final Calendar cal) throws SQLException {
        this._statement.setTimestamp(parameterIndex, x, cal);
    }
    
    @Override
    public void setURL(final int parameterIndex, final URL x) throws SQLException {
        this._statement.setURL(parameterIndex, x);
    }
    
    @Deprecated
    @Override
    public void setUnicodeStream(final int parameterIndex, final InputStream x, final int length) throws SQLException {
        this._statement.setUnicodeStream(parameterIndex, x, length);
    }
    
    @Override
    public Array getArray(final int parameterIndex) throws SQLException {
        return this._statement.getArray(parameterIndex);
    }
    
    @Override
    public Array getArray(final String parameterName) throws SQLException {
        return this._statement.getArray(parameterName);
    }
    
    @Override
    public BigDecimal getBigDecimal(final int parameterIndex) throws SQLException {
        return this._statement.getBigDecimal(parameterIndex);
    }
    
    @Override
    public BigDecimal getBigDecimal(final String parameterName) throws SQLException {
        return this._statement.getBigDecimal(parameterName);
    }
    
    @Deprecated
    @Override
    public BigDecimal getBigDecimal(final int parameterIndex, final int scale) throws SQLException {
        return this._statement.getBigDecimal(parameterIndex, scale);
    }
    
    @Override
    public Blob getBlob(final int parameterIndex) throws SQLException {
        return this._statement.getBlob(parameterIndex);
    }
    
    @Override
    public Blob getBlob(final String parameterName) throws SQLException {
        return this._statement.getBlob(parameterName);
    }
    
    @Override
    public boolean getBoolean(final int parameterIndex) throws SQLException {
        return this._statement.getBoolean(parameterIndex);
    }
    
    @Override
    public boolean getBoolean(final String parameterName) throws SQLException {
        return this._statement.getBoolean(parameterName);
    }
    
    @Override
    public byte getByte(final int parameterIndex) throws SQLException {
        return this._statement.getByte(parameterIndex);
    }
    
    @Override
    public byte getByte(final String parameterName) throws SQLException {
        return this._statement.getByte(parameterName);
    }
    
    @Override
    public byte[] getBytes(final int parameterIndex) throws SQLException {
        return this._statement.getBytes(parameterIndex);
    }
    
    @Override
    public byte[] getBytes(final String parameterName) throws SQLException {
        return this._statement.getBytes(parameterName);
    }
    
    @Override
    public Reader getCharacterStream(final int parameterIndex) throws SQLException {
        return this._statement.getCharacterStream(parameterIndex);
    }
    
    @Override
    public Reader getCharacterStream(final String parameterName) throws SQLException {
        return this._statement.getCharacterStream(parameterName);
    }
    
    @Override
    public Clob getClob(final int parameterIndex) throws SQLException {
        return this._statement.getClob(parameterIndex);
    }
    
    @Override
    public Clob getClob(final String parameterName) throws SQLException {
        return this._statement.getClob(parameterName);
    }
    
    @Override
    public Date getDate(final int parameterIndex) throws SQLException {
        return this._statement.getDate(parameterIndex);
    }
    
    @Override
    public Date getDate(final String parameterName) throws SQLException {
        return this._statement.getDate(parameterName);
    }
    
    @Override
    public Date getDate(final int parameterIndex, final Calendar cal) throws SQLException {
        return this._statement.getDate(parameterIndex, cal);
    }
    
    @Override
    public Date getDate(final String parameterName, final Calendar cal) throws SQLException {
        return this._statement.getDate(parameterName, cal);
    }
    
    @Override
    public double getDouble(final int parameterIndex) throws SQLException {
        return this._statement.getDouble(parameterIndex);
    }
    
    @Override
    public double getDouble(final String parameterName) throws SQLException {
        return this._statement.getDouble(parameterName);
    }
    
    @Override
    public float getFloat(final int parameterIndex) throws SQLException {
        return this._statement.getFloat(parameterIndex);
    }
    
    @Override
    public float getFloat(final String parameterName) throws SQLException {
        return this._statement.getFloat(parameterName);
    }
    
    @Override
    public int getInt(final int parameterIndex) throws SQLException {
        return this._statement.getInt(parameterIndex);
    }
    
    @Override
    public int getInt(final String parameterName) throws SQLException {
        return this._statement.getInt(parameterName);
    }
    
    @Override
    public long getLong(final int parameterIndex) throws SQLException {
        return this._statement.getLong(parameterIndex);
    }
    
    @Override
    public long getLong(final String parameterName) throws SQLException {
        return this._statement.getLong(parameterName);
    }
    
    @Override
    public Reader getNCharacterStream(final int parameterIndex) throws SQLException {
        return this._statement.getNCharacterStream(parameterIndex);
    }
    
    @Override
    public Reader getNCharacterStream(final String parameterName) throws SQLException {
        return this._statement.getNCharacterStream(parameterName);
    }
    
    @Override
    public NClob getNClob(final int parameterIndex) throws SQLException {
        return this._statement.getNClob(parameterIndex);
    }
    
    @Override
    public NClob getNClob(final String parameterName) throws SQLException {
        return this._statement.getNClob(parameterName);
    }
    
    @Override
    public String getNString(final int parameterIndex) throws SQLException {
        return this._statement.getNString(parameterIndex);
    }
    
    @Override
    public String getNString(final String parameterName) throws SQLException {
        return this._statement.getNString(parameterName);
    }
    
    @Override
    public Object getObject(final int parameterIndex) throws SQLException {
        return this._statement.getObject(parameterIndex);
    }
    
    @Override
    public Object getObject(final String parameterName) throws SQLException {
        return this._statement.getObject(parameterName);
    }
    
    @Override
    public Object getObject(final int parameterIndex, final Map<String, Class<?>> map) throws SQLException {
        return this._statement.getObject(parameterIndex, map);
    }
    
    @Override
    public Object getObject(final String parameterName, final Map<String, Class<?>> map) throws SQLException {
        return this._statement.getObject(parameterName, map);
    }
    
    @Override
    public Ref getRef(final int parameterIndex) throws SQLException {
        return this._statement.getRef(parameterIndex);
    }
    
    @Override
    public Ref getRef(final String parameterName) throws SQLException {
        return this._statement.getRef(parameterName);
    }
    
    @Override
    public RowId getRowId(final int parameterIndex) throws SQLException {
        return this._statement.getRowId(parameterIndex);
    }
    
    @Override
    public RowId getRowId(final String parameterName) throws SQLException {
        return this._statement.getRowId(parameterName);
    }
    
    @Override
    public SQLXML getSQLXML(final int parameterIndex) throws SQLException {
        return this._statement.getSQLXML(parameterIndex);
    }
    
    @Override
    public SQLXML getSQLXML(final String parameterName) throws SQLException {
        return this._statement.getSQLXML(parameterName);
    }
    
    @Override
    public short getShort(final int parameterIndex) throws SQLException {
        return this._statement.getShort(parameterIndex);
    }
    
    @Override
    public short getShort(final String parameterName) throws SQLException {
        return this._statement.getShort(parameterName);
    }
    
    @Override
    public String getString(final int parameterIndex) throws SQLException {
        return this._statement.getString(parameterIndex);
    }
    
    @Override
    public String getString(final String parameterName) throws SQLException {
        return this._statement.getString(parameterName);
    }
    
    @Override
    public Time getTime(final int parameterIndex) throws SQLException {
        return this._statement.getTime(parameterIndex);
    }
    
    @Override
    public Time getTime(final String parameterName) throws SQLException {
        return this._statement.getTime(parameterName);
    }
    
    @Override
    public Time getTime(final int parameterIndex, final Calendar cal) throws SQLException {
        return this._statement.getTime(parameterIndex, cal);
    }
    
    @Override
    public Time getTime(final String parameterName, final Calendar cal) throws SQLException {
        return this._statement.getTime(parameterName, cal);
    }
    
    @Override
    public Timestamp getTimestamp(final int parameterIndex) throws SQLException {
        return this._statement.getTimestamp(parameterIndex);
    }
    
    @Override
    public Timestamp getTimestamp(final String parameterName) throws SQLException {
        return this._statement.getTimestamp(parameterName);
    }
    
    @Override
    public Timestamp getTimestamp(final int parameterIndex, final Calendar cal) throws SQLException {
        return this._statement.getTimestamp(parameterIndex, cal);
    }
    
    @Override
    public Timestamp getTimestamp(final String parameterName, final Calendar cal) throws SQLException {
        return this._statement.getTimestamp(parameterName, cal);
    }
    
    @Override
    public URL getURL(final int parameterIndex) throws SQLException {
        return this._statement.getURL(parameterIndex);
    }
    
    @Override
    public URL getURL(final String parameterName) throws SQLException {
        return this._statement.getURL(parameterName);
    }
    
    @Override
    public void registerOutParameter(final int parameterIndex, final int sqlType) throws SQLException {
        this._statement.registerOutParameter(parameterIndex, sqlType);
    }
    
    @Override
    public void registerOutParameter(final String parameterName, final int sqlType) throws SQLException {
        this._statement.registerOutParameter(parameterName, sqlType);
    }
    
    @Override
    public void registerOutParameter(final int parameterIndex, final int sqlType, final int scale) throws SQLException {
        this._statement.registerOutParameter(parameterIndex, sqlType, scale);
    }
    
    @Override
    public void registerOutParameter(final int parameterIndex, final int sqlType, final String typeName) throws SQLException {
        this._statement.registerOutParameter(parameterIndex, sqlType, typeName);
    }
    
    @Override
    public void registerOutParameter(final String parameterName, final int sqlType, final int scale) throws SQLException {
        this._statement.registerOutParameter(parameterName, sqlType, scale);
    }
    
    @Override
    public void registerOutParameter(final String parameterName, final int sqlType, final String typeName) throws SQLException {
        this._statement.registerOutParameter(parameterName, sqlType, typeName);
    }
    
    @Override
    public void setAsciiStream(final String parameterName, final InputStream x) throws SQLException {
        this._statement.setAsciiStream(parameterName, x);
    }
    
    @Override
    public void setAsciiStream(final String parameterName, final InputStream x, final int length) throws SQLException {
        this._statement.setAsciiStream(parameterName, x, length);
    }
    
    @Override
    public void setAsciiStream(final String parameterName, final InputStream x, final long length) throws SQLException {
        this._statement.setAsciiStream(parameterName, x, length);
    }
    
    @Override
    public void setBigDecimal(final String parameterName, final BigDecimal x) throws SQLException {
        this._statement.setBigDecimal(parameterName, x);
    }
    
    @Override
    public void setBinaryStream(final String parameterName, final InputStream x) throws SQLException {
        this._statement.setBinaryStream(parameterName, x);
    }
    
    @Override
    public void setBinaryStream(final String parameterName, final InputStream x, final int length) throws SQLException {
        this._statement.setBinaryStream(parameterName, x, length);
    }
    
    @Override
    public void setBinaryStream(final String parameterName, final InputStream x, final long length) throws SQLException {
        this._statement.setBinaryStream(parameterName, x, length);
    }
    
    @Override
    public void setBlob(final String parameterName, final Blob x) throws SQLException {
        this._statement.setBlob(parameterName, x);
    }
    
    @Override
    public void setBlob(final String parameterName, final InputStream inputStream) throws SQLException {
        this._statement.setBlob(parameterName, inputStream);
    }
    
    @Override
    public void setBlob(final String parameterName, final InputStream inputStream, final long length) throws SQLException {
        this._statement.setBlob(parameterName, inputStream, length);
    }
    
    @Override
    public void setBoolean(final String parameterName, final boolean x) throws SQLException {
        this._statement.setBoolean(parameterName, x);
    }
    
    @Override
    public void setByte(final String parameterName, final byte x) throws SQLException {
        this._statement.setByte(parameterName, x);
    }
    
    @Override
    public void setBytes(final String parameterName, final byte[] x) throws SQLException {
        this._statement.setBytes(parameterName, x);
    }
    
    @Override
    public void setCharacterStream(final String parameterName, final Reader reader) throws SQLException {
        this._statement.setCharacterStream(parameterName, reader);
    }
    
    @Override
    public void setCharacterStream(final String parameterName, final Reader reader, final int length) throws SQLException {
        this._statement.setCharacterStream(parameterName, reader, length);
    }
    
    @Override
    public void setCharacterStream(final String parameterName, final Reader reader, final long length) throws SQLException {
        this._statement.setCharacterStream(parameterName, reader, length);
    }
    
    @Override
    public void setClob(final String parameterName, final Clob x) throws SQLException {
        this._statement.setClob(parameterName, x);
    }
    
    @Override
    public void setClob(final String parameterName, final Reader reader) throws SQLException {
        this._statement.setClob(parameterName, reader);
    }
    
    @Override
    public void setClob(final String parameterName, final Reader reader, final long length) throws SQLException {
        this._statement.setClob(parameterName, reader, length);
    }
    
    @Override
    public void setDate(final String parameterName, final Date x) throws SQLException {
        this._statement.setDate(parameterName, x);
    }
    
    @Override
    public void setDate(final String parameterName, final Date x, final Calendar cal) throws SQLException {
        this._statement.setDate(parameterName, x);
    }
    
    @Override
    public void setDouble(final String parameterName, final double x) throws SQLException {
        this._statement.setDouble(parameterName, x);
    }
    
    @Override
    public void setFloat(final String parameterName, final float x) throws SQLException {
        this._statement.setFloat(parameterName, x);
    }
    
    @Override
    public void setInt(final String parameterName, final int x) throws SQLException {
        this._statement.setInt(parameterName, x);
    }
    
    @Override
    public void setLong(final String parameterName, final long x) throws SQLException {
        this._statement.setLong(parameterName, x);
    }
    
    @Override
    public void setNCharacterStream(final String parameterName, final Reader value) throws SQLException {
        this._statement.setNCharacterStream(parameterName, value);
    }
    
    @Override
    public void setNCharacterStream(final String parameterName, final Reader value, final long length) throws SQLException {
        this._statement.setNCharacterStream(parameterName, value, length);
    }
    
    @Override
    public void setNClob(final String parameterName, final NClob value) throws SQLException {
        this._statement.setNClob(parameterName, value);
    }
    
    @Override
    public void setNClob(final String parameterName, final Reader reader) throws SQLException {
        this._statement.setNClob(parameterName, reader);
    }
    
    @Override
    public void setNClob(final String parameterName, final Reader reader, final long length) throws SQLException {
        this._statement.setNClob(parameterName, reader, length);
    }
    
    @Override
    public void setNString(final String parameterName, final String value) throws SQLException {
        this._statement.setNString(parameterName, value);
    }
    
    @Override
    public void setNull(final String parameterName, final int sqlType) throws SQLException {
        this._statement.setNull(parameterName, sqlType);
    }
    
    @Override
    public void setNull(final String parameterName, final int sqlType, final String typeName) throws SQLException {
        this._statement.setNull(parameterName, sqlType, typeName);
    }
    
    @Override
    public void setObject(final String parameterName, final Object x) throws SQLException {
        this._statement.setObject(parameterName, x);
    }
    
    @Override
    public void setObject(final String parameterName, final Object x, final int targetSqlType) throws SQLException {
        this._statement.setObject(parameterName, x, targetSqlType);
    }
    
    @Override
    public void setObject(final String parameterName, final Object x, final int targetSqlType, final int scale) throws SQLException {
        this._statement.setObject(parameterName, x, targetSqlType, scale);
    }
    
    @Override
    public void setRowId(final String parameterName, final RowId x) throws SQLException {
        this._statement.setRowId(parameterName, x);
    }
    
    @Override
    public void setSQLXML(final String parameterName, final SQLXML xmlObject) throws SQLException {
        this._statement.setSQLXML(parameterName, xmlObject);
    }
    
    @Override
    public void setShort(final String parameterName, final short x) throws SQLException {
        this._statement.setShort(parameterName, x);
    }
    
    @Override
    public void setString(final String parameterName, final String x) throws SQLException {
        this._statement.setString(parameterName, x);
    }
    
    @Override
    public void setTime(final String parameterName, final Time x) throws SQLException {
        this._statement.setTime(parameterName, x);
    }
    
    @Override
    public void setTime(final String parameterName, final Time x, final Calendar cal) throws SQLException {
        this._statement.setTime(parameterName, x, cal);
    }
    
    @Override
    public void setTimestamp(final String parameterName, final Timestamp x) throws SQLException {
        this._statement.setTimestamp(parameterName, x);
    }
    
    @Override
    public void setTimestamp(final String parameterName, final Timestamp x, final Calendar cal) throws SQLException {
        this._statement.setTimestamp(parameterName, x, cal);
    }
    
    @Override
    public void setURL(final String parameterName, final URL val) throws SQLException {
        this._statement.setURL(parameterName, val);
    }
    
    @Override
    public boolean wasNull() throws SQLException {
        return this._statement.wasNull();
    }
    
    @Override
    public void closeOnCompletion() throws SQLException {
        this._statement.closeOnCompletion();
    }
    
    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return this._statement.isCloseOnCompletion();
    }
    
    @Override
    public <T> T getObject(final int parameterIndex, final Class<T> type) throws SQLException {
        return this._statement.getObject(parameterIndex, type);
    }
    
    @Override
    public <T> T getObject(final String parameterName, final Class<T> type) throws SQLException {
        return this._statement.getObject(parameterName, type);
    }
}
